version: "3.9"

services:
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_URLS: http://+:5000
      IS_DOCKER_CONTAINER: true
      DB_STRING: Server=mysql;Database=esm;Uid=root;Pwd=secret;

  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/docker-entrypoint-initdb.d
      - esm-mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret

volumes:
  esm-mysql: